version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: calculadora
    hostname: calculadora
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=true
